server {
    listen 80;
    server_name imagify.com;

    return 301 https://imagify.com$request_uri;
}

server {
    listen 443 ssl;
    server_name imagify.com;

    ssl_certificate /Users/deveshwarthakur/Desktop/Office/Pixora/nginx/ssl/imagify.pem;
    ssl_certificate_key /Users/deveshwarthakur/Desktop/Office/Pixora/nginx/ssl/imagify-key.pem;

    location / {
        proxy_pass http://127.0.0.1:5173;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
